HW45-solution
OleksiiKolinko/book-sore-spring pull request #10
Opened 2023-11-26 04:54 UTC by OleksiiKolinko

2023-11-26 12:33 UTC, kerrrusha requested changes

2023-11-26 12:33 UTC, kerrrusha commented on src/main/java/mate/academy/config/SecurityConfig.java
> +                                .requestMatchers("/auth/**", "/swagger-ui/**", "/categories/**")
why we should allow full access to the `/categories/**` endpoints?
```suggestion
                                .requestMatchers("/auth/**", "/swagger-ui/**")
```

2023-11-26 15:53 UTC, Rommelua commented on src/main/java/mate/academy/dto/book/CreateBookRequestDto.java
> +    private Set<Category> categories = new HashSet<>();
We can not use our entity in DTO

2023-11-26 15:53 UTC, Rommelua commented on src/main/java/mate/academy/repository/book/BookRepository.java
> +    List<Book> findAllByCategoryId(Long categoryId);
do not use nativeQuery when it is possible

2023-11-28 13:49 UTC, kerrrusha approved these changes

2023-11-28 13:55 UTC, merged