HW49-solution
OleksiiKolinko/book-sore-spring pull request #15
Opened 2023-12-12 06:19 UTC by OleksiiKolinko

![test](https://github.com/OleksiiKolinko/book-sore-spring/assets/138433107/062cedcf-cb17-4c3c-bc08-a8a888540ca5)

2023-12-12 12:30 UTC, Sanderfuck requested changes

2023-12-12 12:30 UTC, Sanderfuck commented on src/test/java/mate/academy/controller/BookControllerTest.java
> +    protected static MockMvc mockMvc;
Why protected?

2023-12-12 12:30 UTC, Sanderfuck commented on src/test/java/mate/academy/controller/BookControllerTest.java
> +    private List<BookDto> getBookDtos() {
Private methods place after public

2023-12-12 12:30 UTC, Sanderfuck commented on src/test/java/mate/academy/controller/BookControllerTest.java
> +        return expected;
Create separate templates

2023-12-12 12:30 UTC, Sanderfuck commented on src/test/java/mate/academy/controller/BookControllerTest.java
> +        expected.setCategories(categoryDtos1);
Create templates for clear code

2023-12-12 12:30 UTC, Sanderfuck commented on src/test/java/mate/academy/controller/CategoryControllerTest.java
> +    static void teardown(DataSource dataSource) {
package private modifier for this method?

2023-12-12 12:30 UTC, Sanderfuck commented on src/test/java/mate/academy/service/BookServiceTest.java
> +        CREATE_BOOK_DTO.setCategories(CATEGORY_DTOS);
Create templates

2023-12-12 12:30 UTC, Sanderfuck commented on src/test/java/mate/academy/service/BookServiceTest.java
> +        verifyNoMoreInteractions(bookRepository);
For repository you can use testcontainer instead of mock

2023-12-13 15:32 UTC, kerrrusha approved these changes

2023-12-13 15:40 UTC, merged